### ISSUE TITLE
Wolf definition of LP

### ISSUE THREAD

**Issue by Facuriy** [PaulMelloy/cercospoRa#22]
in wolf 2005 the formula for latent period has an error, it lacks negative sign to the exponent. 
![image](https://github.com/user-attachments/assets/62b71e24-8c07-4408-94da-0387a9d5ea10)
from:
Wolf, P. F. J.; Verreet, J. A. 2005
Factors affecting the onset of cercospora leaf spot epidemics in sugar beet and establishment of disease-monitoring thresholds
10.1094/PHYTO-95-0269
however in older literature where the generated formula comes from it is correct.
![image](https://github.com/user-attachments/assets/0445edc3-cfed-4527-a0f6-31dc5398480a)
from:
P. F. J. Wolf; Heindl, M.; Verreet, J. A. 2001
Zum Einfluß des Bestandesklimas auf die Prädisposition der Zuckerrübe gegenüber Infektionen von Cercospora beticola (Sacc.) Influence of sugar beet leaf mass development on predisposition of the crop to Cerco- spora beticola (Sacc.)
https://www.researchgate.net/publication/237563305_Zum_Einfluss_des_Bestandesklimas_auf_die_Pradisposition_der_Zuckerrube_gegenuber_Infektionen_von_Cercospora_beticola_Sacc_Influence_of_sugar_beet_leaf_mass_development_on_predisposition_of_the_crop_to

**Comment by PaulMelloy** [comment]
Thanks Facundo,

I noticed this is a error in wolf and Verreet's paper. The formula in the package to return latent period produces the following plot

```r
plot(latent_period(9:35), x = 9:35, 
     xlab = "Temperature C",
     ylab = "days",
     pch = 16)
```

![image](https://github.com/user-attachments/assets/ff49f9de-4f4c-49e0-ad99-6eada0e98a16)

If I go in and change `-0.35` to `0.35` the following response is given for the same code above.

![image](https://github.com/user-attachments/assets/abbc54c6-0541-4e2d-a0ce-af37e4f738f0)
