### ISSUE TITLE
calc_DIV.R and latent_period.R

### ISSUE THREAD

**Issue by ReneHeim** [PaulMelloy/cercospoRa#7]
I have been testing the functions using the pre-installed Brisbane data and now also using 27 different weather stations in our sugar beet trial. Without failure, calc_DIV() works as expected. And as far as I understand, both Racca DIV and DIV use latent_period.R to generate the moisture and temperature index. However, when trying to run moisture and temperature index as stand-alone functions (also using latent_period.R), then I receive the following error message:

Error in latent_period(dfs[[1]]$temp, ref = "wolf") : 
  could not find function "latent_period"

**Comment by PaulMelloy** [comment]
This might be because `latent_period()` is not an exported function. That means it is not available to people installing the package, it is only available when working on the  package repo and using the `devtools::load_all()` function
