### ISSUE TITLE
Both, Racca and Wolf use DIV. But in the literature, DIV only occurs in Wolf

### ISSUE THREAD

**Issue by ReneHeim** [PaulMelloy/cercospoRa#8]
https://github.com/PaulMelloy/cercosporaR/blob/5a3ae2aacebc72afb3d6d43831529703762c4a17/R/calc_DIV.R#L77

I am confused about the way DIV is calculated for Wolf AND for Racca. Wolf originally came up with the idea to calculate a temperature and a moisture index:

![image](https://github.com/PaulMelloy/cercosporaR/assets/24690333/d4a8e0b9-eb50-497e-973c-860dccea733c)

However, Racca uses the incubation (INC), sporulation (SPOR), and infection rate (IFR) to calculate daily infection pressure (which is admittedly similar to DIV). My question is, is it okay if you just use the temperature and moisture index originally by Wolf to also calculate a "DIV" version of Racca?

![image](https://github.com/PaulMelloy/cercosporaR/assets/24690333/cb404ceb-13b6-490a-bed4-5c9e11a42aac)

**Comment by PaulMelloy** [comment]
The Racca model is more complex and incorporates additional disease processes, such as Spore Rate, and infection Rate. The Wolf model tracks the process of the disease epidemic by calculating the time during conducive conditions. Its simpler, but sometimes a more stable way of estimating epidemics, but less accurate and less adjustable.

**Comment by PaulMelloy** [comment]
The [Racca model](https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1365-2338.2007.01136.x) calculates disease incidence on a daily timestep $DI_{i}$. This is calculated as a cumulative sum over time.

Similary the wolf model is calculated on a daily timestep, but the values which are calculated there are $DIV_{k}$ as described above. 

The version [plus_racca](https://github.com/PaulMelloy/cercospoRa/tree/plus_racca) that includes both Wolf and Racca model outputs, calculates both these values separately and reports them in a list length of two, each element the output of each respective model.
